name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Chrisdroid1"
          replace: "FireXbot"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'SeD Replacer'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: AT-WORLDS-END
          commit_user_email: rahulkharbash1259@gmail.com
          commit_author: AT-WORLDS-END <rahulkharbash1259@gmail.com>
